### ISSUE TITLE
[B2][3] Boss battle disappeared!!

### ISSUE THREAD

**Issue by jerrodstorm** [TravelSizedLions/journey#142]
The boss battle didn't load! This was on ultrawidescreen

**Comment by hiltonjp** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Boss battle disappears with ultrawide resolution](https://trello.com/c/D3hrpPQn/46-boss-battle-disappears-with-ultrawide-resolution)

**Comment by jerrodstorm** [comment]
This got fixed some time ago, I believe.
