### ISSUE TITLE
[T3][1] Players can have trouble recognizing blizz at the start

### ISSUE THREAD

**Issue by jerrodstorm** [TravelSizedLions/journey#172]
Since Blizz starts out as a semi-transparent ball, it can be a little hard for some to recognize that she's someone that needs to be talked to. This was noticed during a in-person playtest, where the player walked right past blizz even though there was a speech bubble indicator.

**Comment by hiltonjp** [comment]
Will get fixed when https://github.com/TheHumanBuilders/journey/issues/173 is done

**Comment by jerrodstorm** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[demo] ship section polish](https://trello.com/c/ELJi8zhl/84-demo-ship-section-polish)
