### ISSUE TITLE
[T2][1] Leaving the med-bay before talking to blizz should change her dialog to something else.

### ISSUE THREAD

**Issue by jerrodstorm** [TravelSizedLions/journey#173]

**Comment by hiltonjp** [comment]
Or just make the conversation mandatory.

**Comment by jerrodstorm** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[demo] ship section polish](https://trello.com/c/ELJi8zhl/84-demo-ship-section-polish)
