### ISSUE TITLE
[B2][3] Landing on Corners Breaks Physics

### ISSUE THREAD

**Issue by jerrodstorm** [TravelSizedLions/journey#187]
If you:
1. jump while standing next to a short wall
2. then let yourself fall back down, hitting the corner of the small wall

Then:
- You are teleported in the direction of the wall you were jumping against.

**Comment by hiltonjp** [comment]
Probably has something to do with the way the player character projects against walls for wallsliding.

**Comment by jerrodstorm** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[demo] quality pass](https://trello.com/c/e0DcYIiT/85-demo-quality-pass)
