### ISSUE TITLE
[B2][2] Decision buttons don't dissappear after a scene transition.

### ISSUE THREAD

**Issue by jerrodstorm** [TravelSizedLions/journey#78]
![image](https://user-images.githubusercontent.com/35467792/93551458-8946fa80-f933-11ea-95fa-0e4ea3dc3d28.png)

So...apparently this is a thing.

This happened when racing through blizz's dialog in the cockpit.

**Comment by hiltonjp** [comment]
I'm guessing I can just have the dialog manager preamaturely end any conversation on scene transition, and double check that these buttons get destroyed.
